name: my_di
description: feature my di package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  my_data:
    path: ../data
  my_domain:
    path: ../domain
  my_presentation:
    path: ../presentation

  core_flutter_bloc:
    path: ../../../core/flutter_bloc
  core_util:
    path: ../../../core/util

  tool_clind_network:
    path: ../../../tool/clind/network