name: my_presentation
description: feature my presentation package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  my_domain:
    path: ../domain

  core_bloc:
    path: ../../../core/bloc
  core_util:
    path: ../../../core/util