name: my_domain
description: feature my domain package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  core_util:
    path: ../../../core/util

  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

dev_dependencies:
  analyzer: 6.11.0
  build_runner: 2.5.3
  freezed: 2.5.2
  json_serializable: 6.7.1
